# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 509280e70b710e4b03d7d4b0194d27e0f278c7e5e081305641dd96d33e8395ba316eb9b45d3392b2156993f506e4c4b4d02d5eb0bf14c20b0f16a15696dade6a

test:
  secret_key_base: 0893f937650923773b8cf33b27275f6dadd3dc9502770fbf1d42c264bd9ac450ef8d93cb65eb943462fe361952011cbbedbc3e3322e422c3ecaaac32d2a0b8b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
